[package]
name = "incpa-recursive"
version.workspace = true
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
derive-new.workspace = true
incpa.workspace = true
